# Generated by Django 3.2.7 on 2021-11-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211104_0700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rank',
            new_name='rate',
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
