# Generated by Django 3.2.7 on 2021-12-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
