# Generated by Django 3.2.7 on 2021-12-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(default='product/default_image.png', upload_to='')),
            ],
        ),
    ]
