# Generated by Django 3.2.9 on 2021-12-11 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_rename_product_subscription_pid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='pid',
            new_name='product',
        ),
    ]
